### PR TITLE
Backport upstream patches

### PR DESCRIPTION
**Pull request by hustliyilin**
These patches are both from openssl upstream(`openssl 1.1.1i`) and the redhat `openssl-1.1.1g.src.rpm`.  

we backport them to babassl with almost no modification except the third patch which discards the change of Copyright years。

### CODE REVIEW

**Comment by hustliyilin** [comment]
It seems both the `out-of-tree_build` and `check_update` CI/CD failed because in the third patch of this pr `ASN1_F_ASN1_ITEM_EX_I2D`  has a collison code(144) with ASN1_F_DC_NEW in the `include/openssl/asn1err.h` file. 

Do you have any special suggestions to solve the code conflict problem of this upstream patch? @uudiin @dongbeiouba @jinjiu  , Thanks a lot

**Comment by dongbeiouba** [comment]
> It seems both the `out-of-tree_build` and `check_update` CI/CD failed because in the third patch of this pr `ASN1_F_ASN1_ITEM_EX_I2D` has a collison code(144) with `ASN1_F_DC_NEW` in the `include/openssl/asn1err.h` file.
> 
> Do you have any special suggestions to solve the code conflict problem of this upstream patch? @uudiin @dongbeiouba @jinjiu , Thanks a lot

You can choose another value for ASN1_F_ASN1_ITEM_EX_I2D.

**Comment by hustliyilin** [comment]
> 
> 
> > It seems both the `out-of-tree_build` and `check_update` CI/CD failed because in the third patch of this pr `ASN1_F_ASN1_ITEM_EX_I2D` has a collison code(144) with `ASN1_F_DC_NEW` in the `include/openssl/asn1err.h` file.
> > Do you have any special suggestions to solve the code conflict problem of this upstream patch? @uudiin @dongbeiouba @jinjiu , Thanks a lot
> 
> You can choose another value for ASN1_F_ASN1_ITEM_EX_I2D.

Thanks a lot, I think may be it's better to re-choose another values for `ASN1_F_DC_NEW` and
`ASN1_F_DC_NEW_FROM_RAW_BYTE`  In order to keep the compatibility with
OpenSSL.  So I create a new pr  #86  to do this.  @dongbeiouba  @uudiin

**Comment by InfoHunter** [comment]
#86 has been merged, you can proceed on this one now. @hustliyilin

**Comment by hustliyilin** [comment]
> #86 has been merged, you can proceed on this one now. @hustliyilin

OK, thanks.

**Review by uudiin — APPROVED** [review]

**Review by InfoHunter — APPROVED** [review]

**Pull request merged**
