### PR TITLE
Add support for wrap mode with openssl enc

### PR DESCRIPTION
**Pull request by dongbeiouba**

### CODE REVIEW

**Comment by InfoHunter** [comment]
What is this patch aimed at?

**Comment by dongbeiouba** [comment]
> What is this patch aimed at?

openssl enc -list contains some wrap ciphers, such as  id-aes256-wrap, but openssl enc -id-aes256-wrap failed.

Get following error message:

> Error setting cipher id-aes256-wrap
> 140657461879936:error:0607B0AA:digital envelope routines:EVP_CipherInit_ex:wrap mode not allowed:crypto/evp/evp_enc.c:189:

After setting EVP_CIPHER_CTX_FLAG_WRAP_ALLOW flag, it's OK to use openssl enc  to encrypt files with wrap modes.

**Comment by InfoHunter** [comment]
Do you mind to add some test cases for this

**Comment by InfoHunter** [comment]
CI failures are very related. Need to be fixed.

**Comment by dongbeiouba** [comment]
Fix 3des-wrap encryption bug. Please refer to [openssl#16002](https://github.com/openssl/openssl/pull/16002)

**Review by InfoHunter — APPROVED** [review]

**Pull request merged**
